#!/usr/bin/perl -wT
# 
# started by Matija Nalis <mnalis-git@voyager.hr> 2019-07-01
#
# parses standard mysqldump one-file-dump, and reimports it in parallel 
# to speed up restoring database.
#

use strict;
use autodie;

my $cur_fd = undef;
my $file_seq = 0;

# closes previous, and opens a new file
sub open_file($) {
	my ($basename) = @_;
	my $new_fname = 'tmp/mysql-prestore.' . $basename;
	close $cur_fd if defined $cur_fd;
	open $cur_fd, '>', $new_fname;
}

# opens next file for next table
sub open_next() {
	my $base = sprintf ('table%.6d', $file_seq++);
	open_file($base);
}

open_file('head');

while (<STDIN>) {
	open_next() if /^-- Table structure/;
	open_file('tail') if /^-- Dump completed/;
	print $cur_fd $_;
}

close $cur_fd;
